# Generated by Django 5.2 on 2025-04-15 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rewardlog',
            options={'verbose_name': 'Журнал наград', 'verbose_name_plural': 'Журналы наград'},
        ),
        migrations.AlterModelOptions(
            name='scheduledreward',
            options={'verbose_name': 'Запланированная награда', 'verbose_name_plural': 'Запланированные награды'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
