# Generated by Django 5.2 on 2025-04-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_alter_rewardlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardlog',
            name='requested_by_user',
            field=models.BooleanField(default=False, verbose_name='Запрошено пользователем'),
        ),
        migrations.AddField(
            model_name='scheduledreward',
            name='requested_by_user',
            field=models.BooleanField(default=False, verbose_name='Запрошено пользователем'),
        ),
    ]
